
spring:
  application:
    name: eureka-server
  profiles: discovery1
server:
  port: 8761
eureka:
  instance:
    hostname: discovery1
  client:
    register-with-eureka: true
    fetch-registry: true
    preferIpAddress: false
    serviceUrl:
      defaultZone: http://discovery2:8762/eureka/,http://discovery3:8763/eureka/
---

spring:
  application:
    name: eureka-server
  profiles: discovery2
server:
  port: 8762
eureka:
  instance:
    hostname: discovery2
  client:
    register-with-eureka: true
    fetch-registry: true
    preferIpAddress: false
    serviceUrl:
      defaultZone: http://discovery1:8761/eureka/,http://discovery3:8763/eureka/
---
spring:
  application:
    name: eureka-server
  profiles: discovery3
server:
  port: 8763
eureka:
  instance:
    hostname: discovery3
  client:
    fetch-registry: true
    register-with-eureka: true
    preferIpAddress: false
    serviceUrl:
      defaultZone: http://discovery1:8761/eureka/,http://discovery2:8762/eureka/
